### ISSUE TITLE
`client.generateStylesFromContent` is not a function

### ISSUE THREAD

**Issue by mhsdesign** [remcohaszing/monaco-tailwindcss#53] opened 2022-05-09 12:03 UTC
i just came accross this console error:
a second ago it was working, will investigate what the reason for this behaviour was in my case.

```
Uncaught (in promise) TypeError: client.generateStylesFromContent is not a function
    at Object.generateStylesFromContent (index.ts:75:23)
```

https://github.com/remcohaszing/monaco-tailwindcss/blob/11c599151ad04ae54354dd95e1afcafcda131999/src/index.ts#L75

**Comment by remcohaszing** [comment] 2022-06-03 14:00
This was caused by an upstream bug in `monaco-worker-manager` and has been fixed in [v2.0.1](https://github.com/remcohaszing/monaco-worker-manager/releases/tag/v2.0.1)

**Closed** 2022-06-03 14:23 UTC

**Comment by mhsdesign** [comment] 2022-06-03 18:04
thanks, how did you find out what the reason was? great!

**Comment by remcohaszing** [comment] 2022-06-04 10:07
https://github.com/remcohaszing/monaco-worker-manager/commit/8039f6f46c91e70608431f63c6da36838c11118c fixed it.

The client is undefined, and comes from `getWorker()`. There was only one statement between the assignment of the client and the return statement. This is an async call, meaning the only reason it can be undefined, is if the timeou unsets it while the async statement was being processed.

I found a setup where this error occurred more often, I don’t know why. It’s a fairly random issue, but this allowed me to troubleshoot it.

**Comment by mhsdesign** [comment] 2022-06-04 10:17
Ah now it makes sense ;) Thanks ^^
